name: CI
on:
  push:
    branches:
    - main
    - m1-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  generate-macos-launcher:
    timeout-minutes: 120
    runs-on: "macOS-m1"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/setup-action@f883d08305acbc28e5e5363bf5ec086397627021
      with:
        apps: ""
        jvm: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-darwin-aarch64-22.1.0.tar.gz"
    - name: Generate native launcher
      run: .github/scripts/generate-native-image.sh
    - run: ./mill -i ci.setShouldPublish
    - name: Build OS packages
      if: env.SHOULD_PUBLISH == 'true'
      run: .github/scripts/generate-os-packages.sh
    - name: Copy artifacts
      run: ./mill -i copyDefaultLauncher artifacts/
    - uses: actions/upload-artifact@v3
      with:
        name: macos-launchers
        path: artifacts/
        if-no-files-found: error
        retention-days: 1

  native-macos-tests-1:
    needs: generate-macos-launcher
    timeout-minutes: 120
    runs-on: "macOS-m1"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/setup-action@f883d08305acbc28e5e5363bf5ec086397627021
      with:
        apps: ""
        jvm: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-darwin-aarch64-22.1.0.tar.gz"
    - uses: actions/download-artifact@v3
      with:
        name: macos-launchers
        path: artifacts/
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Native integration tests
      run: ./mill -i nativeIntegrationTests
      env:
        UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCALA_CLI_IT_FORCED_LAUNCHER_DIRECTORY: artifacts/
        SCALA_CLI_IT_GROUP: 1
        SCALA_CLI_SODIUM_JNI_ALLOW: false
